fix issues, creates re-usable components
streetlives/yourpeer.nyc-django pull request #113
Opened 2024-05-15 11:47 UTC by shakilhossain1

2024-05-22 00:54 UTC, jbeard4 requested changes

2024-05-22 00:54 UTC, jbeard4 commented on components/location_service/location_service.py
> +class Calendar(component.Component):
This class name of this component probably shouldn't be called `Calendar`

2024-05-22 00:54 UTC, jbeard4 commented on components/location_service/location_service.py
> +    # This component takes one parameter, a service_info string to show in the template
This comment seems inaccurate. It looks like this component takes 3 parameters.

2024-05-22 00:54 UTC, jbeard4 commented on components/location_service/location_service.py
> +    # This component takes one parameter, a service_info string to show in the template
Also, service_info is not a string, it's an object.

2024-05-22 00:54 UTC, jbeard4 commented on config/settings.py
> +STATICFILES_DIRS = [str(BASE_DIR.joinpath("static")), os.path.join(BASE_DIR, "components"),]
I don't think the components directory is meant to be served as static file.
```suggestion
STATICFILES_DIRS = [str(BASE_DIR.joinpath("static"))]
```

2024-05-22 00:54 UTC, jbeard4 commented on templates/location_details.html
> +      {% component "location_service" service_info=location.personal_care_services name="Personal care" icon="dist/img/icons/personal-care-icon.png" %}{% endcomponent %}
This is a good cleanup. Lots off duplicate code removed.

2024-05-29 16:05 UTC, jbeard4 commented on config/settings.py
> +STATICFILES_DIRS = [str(BASE_DIR.joinpath("static")), os.path.join(BASE_DIR, "components")]
@shakilhossain1  Why was this restored?

2024-06-05 13:32 UTC, shakilhossain1 commented on config/settings.py
> +STATICFILES_DIRS = [str(BASE_DIR.joinpath("static")), os.path.join(BASE_DIR, "components")]
otherwise the django-component package won't working!

2024-06-10 21:23 UTC, merged